version: '3.8'

networks:
  aegis-network:
    driver: bridge

volumes:
  orderer.aegis.com:
  peer0.org1.aegis.com:
  peer0.org2.aegis.com:

services:
  orderer.aegis.com:
    container_name: orderer.aegis.com
    image: hyperledger/fabric-orderer:2.5.0
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/aegis.com/orderers/orderer.aegis.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/aegis.com/orderers/orderer.aegis.com/tls/:/var/hyperledger/orderer/tls
      - orderer.aegis.com:/var/hyperledger/production/orderer
    ports:
      - "7050:7050"
    networks:
      - aegis-network

  peer0.org1.aegis.com:
    container_name: peer0.org1.aegis.com
    image: hyperledger/fabric-peer:2.5.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=aegis-network_aegis-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ID=peer0.org1.aegis.com
      - CORE_PEER_ADDRESS=peer0.org1.aegis.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.aegis.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.aegis.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.aegis.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.aegis.com/peers/peer0.org1.aegis.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.aegis.com/peers/peer0.org1.aegis.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org1.aegis.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "7051:7051"
    depends_on:
      - orderer.aegis.com
    networks:
      - aegis-network

  peer0.org2.aegis.com:
    container_name: peer0.org2.aegis.com
    image: hyperledger/fabric-peer:2.5.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=aegis-network_aegis-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ID=peer0.org2.aegis.com
      - CORE_PEER_ADDRESS=peer0.org2.aegis.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.aegis.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.aegis.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.aegis.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.aegis.com/peers/peer0.org2.aegis.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.aegis.com/peers/peer0.org2.aegis.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org2.aegis.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "9051:9051"
    depends_on:
      - orderer.aegis.com
    networks:
      - aegis-network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5.0
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.aegis.com/users/Admin@org1.aegis.com/msp
      - CORE_PEER_ADDRESS=peer0.org1.aegis.com:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0.org1.aegis.com
      - peer0.org2.aegis.com
      - orderer.aegis.com
    networks:
      - aegis-network

